"""add device history audit trail

Revision ID: 21d3fe1482c5
Revises: 0642377e4311
Create Date: 2026-04-09 08:22:10.481620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d3fe1482c5'
down_revision = '0642377e4311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.String(length=512), nullable=True),
    sa.Column('new_value', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_history_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_history_device_id'))

    op.drop_table('device_history')
    # ### end Alembic commands ###
