"""remove site_abb from site

Revision ID: 3157ebf5d70c
Revises: bc8ce8723e62
Create Date: 2026-03-25 21:50:49.773835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3157ebf5d70c'
down_revision = 'bc8ce8723e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_index('site_abb')
        batch_op.drop_column('site_abb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_abb', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index('site_abb', ['site_abb'], unique=True)

    # ### end Alembic commands ###
