"""add ftp schedule start stop date

Revision ID: 3772e0ac4ae5
Revises: 4d1fa402a3ad
Create Date: 2026-04-08 18:37:35.280114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3772e0ac4ae5'
down_revision = '4d1fa402a3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp_schedule_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ftp_schedule_stop_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('ftp_schedule_stop_date')
        batch_op.drop_column('ftp_schedule_start_date')

    # ### end Alembic commands ###
