"""add email config to organization

Revision ID: 64865d4f15ef
Revises: 3157ebf5d70c
Create Date: 2026-03-26 21:22:07.445134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64865d4f15ef'
down_revision = '3157ebf5d70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_server', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mail_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mail_use_tls', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mail_use_ssl', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mail_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mail_password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mail_default_sender', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('mail_default_sender')
        batch_op.drop_column('mail_password')
        batch_op.drop_column('mail_username')
        batch_op.drop_column('mail_use_ssl')
        batch_op.drop_column('mail_use_tls')
        batch_op.drop_column('mail_port')
        batch_op.drop_column('mail_server')

    # ### end Alembic commands ###
