"""add index on bulk_upload_log.uploaded_at

Revision ID: 7ffaf7e10b12
Revises: 21d3fe1482c5
Create Date: 2026-04-14 19:30:35.535232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ffaf7e10b12'
down_revision = '21d3fe1482c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_upload_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_upload_log_uploaded_at'), ['uploaded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_upload_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_upload_log_uploaded_at'))

    # ### end Alembic commands ###
