"""add ftp config and bulk upload log

Revision ID: c8f02781111b
Revises: 37be27bcf3aa
Create Date: 2026-04-02 20:33:01.714583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f02781111b'
down_revision = '37be27bcf3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_upload_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('users_added', sa.Integer(), nullable=True),
    sa.Column('users_updated', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp_host_enc', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('ftp_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ftp_username_enc', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('ftp_password_enc', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('ftp_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('ftp_use_tls', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ftp_schedule_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ftp_schedule_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ftp_schedule_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ftp_schedule_days', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ftp_last_run_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ftp_last_run_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['site_acronyms'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('ftp_last_run_status')
        batch_op.drop_column('ftp_last_run_at')
        batch_op.drop_column('ftp_schedule_days')
        batch_op.drop_column('ftp_schedule_minute')
        batch_op.drop_column('ftp_schedule_hour')
        batch_op.drop_column('ftp_schedule_enabled')
        batch_op.drop_column('ftp_use_tls')
        batch_op.drop_column('ftp_path')
        batch_op.drop_column('ftp_password_enc')
        batch_op.drop_column('ftp_username_enc')
        batch_op.drop_column('ftp_port')
        batch_op.drop_column('ftp_host_enc')

    op.drop_table('bulk_upload_log')
    # ### end Alembic commands ###
