"""add device_tag to device

Revision ID: d6898ec7cbee
Revises: f331225e6564
Create Date: 2026-03-06 19:43:23.857496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6898ec7cbee'
down_revision = 'f331225e6564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_tag', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('device_tag')

    # ### end Alembic commands ###
