"""make return_at nullable

Revision ID: eab82b7a0587
Revises: 
Create Date: 2026-03-03 19:49:03.287657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eab82b7a0587'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('return_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('patron', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['badge_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patron', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('return_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
