"""add guardian_name and phone to patron

Revision ID: f331225e6564
Revises: eab82b7a0587
Create Date: 2026-03-03 21:43:38.615840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f331225e6564'
down_revision = 'eab82b7a0587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patron', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patron', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('guardian_name')

    # ### end Alembic commands ###
